ENV['SHELL_SCRIPT'] ||= 'docker'

ENV['SHELL_LOGNAME'] ||= 'root'
ENV['SHELL_SSH_PRIVATE'] = "#{ENV['HOME']}/.vagrant.d/insecure_private_key"

require "vagrant-shell"
require "vagrant-shell/ssh-agent"
require "vagrant-shell/env-config"

Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-shell"
  config.ssh.username = (ENV['SHELL_LOGNAME'] || ENV['LOGNAME']) if ENV['SHELL_LOGNAME']
  config.ssh.private_key_path = ENV['SHELL_SSH_PRIVATE'] if ENV['SHELL_SSH_PRIVATE']

  script = ENV['SHELL_SCRIPT']
  releases = Array(ENV['SHELL_IMAGE'] || %w(ubuntu:precise ubuntu:quantal))

  releases.each do |release|
    config.vm.define release.to_sym do |guest|
      guest.vm.provider script.to_sym do |shell, override|
        shell.image = release
        shell.script = shell.find_script(script)
        shell.run_args = [ "bash -c '#{shell.read_script(File.expand_path("../libexec/init-docker", __FILE__))}'" ]
      end
    end
  end
end
