require "vagrant-shell"
require "vagrant-shell/ssh-agent"

VagrantPlugins::Shell::Plugin.make_provider(:static)

Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-shell"
  config.ssh.username = ENV['LOGNAME']

  config.vm.provider :static do |shell, override|
    shell.image = 'localhost'
    shell.script = shell.find_script(:static)
  end
end
