#!/bin/bash -efu

if [[ -n "${VAGRANT_LOG:-}" ]]; then
  set -x
fi

cmd="$1"; shift
case "$cmd" in
  run-instance)
    image="$1"; shift
    docker run -d "$image" "$@"
    ;;
  terminate-instance)
    instance="$1"; shift
    docker stop "$instance" 
    ;;
  ssh-info)
    instance="$1"; shift
    echo "$(docker inspect $instance | awk '$1 ~ /IpAddress/ { split($2,ip,"\""); print ip[2] }')" 22
    ;;
  read-state)
    instance="$1"; shift
    echo "$(docker inspect $instance | awk '$1 ~ /Running/ { split($2,state,","); print(state[1] == "true" ? "running" : "not_created") }')"
    ;;
  *)
    exit 1
    ;;
esac
