# load the shell provider as it was not installed as a plugin
require "vagrant-shell"
require "vagrant-shell/ssh-agent"
require "vagrant-shell/env-config"

Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-shell"
  config.ssh.username = (ENV['SHELL_LOGNAME'] || ENV['LOGNAME']) if ENV['SHELL_LOGNAME']
  config.ssh.private_key_path = ENV['SHELL_SSH_PRIVATE'] if ENV['SHELL_SSH_PRIVATE']

  script = ENV['SHELL_SCRIPT']
  case script
  when "aws"
    config.vm.provider script.to_sym do |shell, override|
      shell.image = ENV['SHELL_IMAGE'] if ENV['SHELL_IMAGE']
      shell.script = shell.find_script(script)
    end
  when "static"
    config.vm.provider script.to_sym do |shell, override|
      shell.image = ENV['SHELL_IMAGE'] if ENV['SHELL_IMAGE']
      shell.script = shell.find_script(script)
    end
  when "docker"
    config.vm.provider script.to_sym do |shell, override|
      shell.image = ENV['SHELL_IMAGE'] if ENV['SHELL_IMAGE']
      shell.script = shell.find_script(script)
      shell.run_args = [ "bash -c '#{shell.read_script File.expand_path("../../libexec/init-docker", __FILE__)}'" ]
    end
  end
end
