ENV['SHELL_SCRIPT'] ||= 'ec2'

ENV['SHELL_LOGNAME'] ||= 'ubuntu'

require "vagrant-shell"
require "vagrant-shell/ssh-agent"
require "vagrant-shell/env-config"

Vagrant.configure("2") do |config|
  config.vm.box = "vagrant-shell"
  config.ssh.username = (ENV['SHELL_LOGNAME'] || ENV['LOGNAME']) if ENV['SHELL_LOGNAME']
  config.ssh.private_key_path = ENV['SHELL_SSH_PRIVATE'] if ENV['SHELL_SSH_PRIVATE']

  script = ENV['SHELL_SCRIPT']
  config.vm.provider script.to_sym do |shell, override|
    shell.image = ENV['SHELL_IMAGE'] if ENV['SHELL_IMAGE']
    shell.script = shell.find_script(script)
  end
end
